/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsIdRouteRouteImport } from './routes/projects/$id/route'

const IndexLazyRouteImport = createFileRoute('/')()
const ProjectsIdIndexLazyRouteImport = createFileRoute('/projects/$id/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectsIdRouteRoute = ProjectsIdRouteRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexLazyRoute = ProjectsIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any).lazy(() =>
  import('./routes/projects/$id/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects/$id': typeof ProjectsIdRouteRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projects/$id': typeof ProjectsIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/projects/$id': typeof ProjectsIdRouteRouteWithChildren
  '/projects/$id/': typeof ProjectsIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$id' | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$id'
  id: '__root__' | '/' | '/projects/$id' | '/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsIdRouteRoute: typeof ProjectsIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexLazyRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
  }
}

interface ProjectsIdRouteRouteChildren {
  ProjectsIdIndexLazyRoute: typeof ProjectsIdIndexLazyRoute
}

const ProjectsIdRouteRouteChildren: ProjectsIdRouteRouteChildren = {
  ProjectsIdIndexLazyRoute: ProjectsIdIndexLazyRoute,
}

const ProjectsIdRouteRouteWithChildren = ProjectsIdRouteRoute._addFileChildren(
  ProjectsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsIdRouteRoute: ProjectsIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
